# Generated by Django 5.1.2 on 2024-11-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_show_create_at_show_created_at_show_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='create_at',
        ),
    ]
